author/urls.py
from django.urls import path

from . import views

app_name = "author"

urlpatterns = [
	path("",views.connect,name="connect"),
	path("<slug:slug>",views.author,name="author"),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
	path("",views.posts,name="posts"),
	path("<slug:slug>",views.post,name="post"),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home,name="home"),
]

rhosdiary/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("main.urls")),
    path("connect/",include("author.urls")),
    path("blog/",include("blog.urls")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

author/models.py
from datetime import datetime

from django.db import models

# Create your models here.
class Author(models.Model):
	first_name = models.CharField(max_length=200,default="Oghenerhona")
	last_name = models.CharField(max_length=200,default="Ideh")
	snap = models.ImageField(upload_to='data/%Y/%m/%d/',blank =True)
	description = models.TextField(blank=True)
	phone = models.CharField(max_length=20)
	email = models.CharField(max_length=50)
	instagram = models.CharField(max_length=50,blank=True)
	date_joined = models.DateTimeField(default=datetime.now, blank=True)
	slug = models.SlugField(max_length=50,default="oghenerhona-ideh")
	value_1 = models.CharField(max_length=50,default="Journalist")
	value_2 = models.CharField(max_length=50,default="Beautiful")
	
	def __str__(self):
		return self.first_name

blog/models.py
from datetime import datetime

from django.db import models

from ckeditor_uploader.fields import RichTextUploadingField

from author.models import Author

# Create your models here.
class Article(models.Model):
	blog_author = models.ForeignKey(Author, on_delete=models.DO_NOTHING)
	blog_title = models.CharField(max_length=200)
	blog_content = RichTextUploadingField()
	blog_time = models.DateTimeField(default=datetime.now)
	is_published = models.BooleanField(default=True) 	
	blog_url = models.SlugField(max_length=200)
	short_description = models.CharField(max_length=200)
	blog_photo = models.ImageField(upload_to='assets/%Y/%m/%d/',default='/media/assets/default.jpg', null = True)
    #blog_photo_1 = models.ImageField(upload_to='assets/%Y/%m/%d/',blank =True)

	def __str__(self):
		return self.blog_title

main/models.py
from django.db import models

# Create your models here.

author/views.py
from django.shortcuts import get_object_or_404,render

from .models import Author
# Create your views here.
def connect(request):
	writers = Author.objects.all()
	frontend = {
		"writers":writers
	}

	return render(request,"author/connect.html",frontend)

def author(request,slug):
	writers = get_object_or_404(Author, slug=slug)
	frontend = {
		"writers": writers
	}
	return render(request,"author/author.html",frontend)

blog/views.py
from django.shortcuts import get_object_or_404,render
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from .models import Article
# Create your views here.
def posts(request):
	article_content = Article.objects.order_by("-blog_time").filter(is_published=True)

	paginator = Paginator(article_content, 4)
	page = request.GET.get('page')
	paged_articles = paginator.get_page(page)

	frontend = {
		"article_content": paged_articles
	}

	return render(request,"blog/posts.html",frontend)

def post(request,slug):
	blog = get_object_or_404(Article, blog_url=slug)
	
	frontend = {
		"blog": blog
	}

	return render(request,"blog/post.html",frontend)

main/views.py
from django.shortcuts import render

from blog.models import Article
from author.models import Author
# Create your views here.
def home(request):
	article_content = Article.objects.all().order_by("-blog_time").filter(is_published=True)[:3]
	writers = Author.objects.all()
	frontend = {
		"article_content": article_content,
		"writers":writers
	}

	return render(request,"main/home.html",frontend)

def navbar(request):
	return render(request,"base.html",frontend)

templates/author/author.html
{% load static %}
<!DOCTYPE html>
<html lang="en-us">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <title>I am {{ writers.first_name }}</title>
    <meta name="author" content="Eyimofe" />
    <meta name="description" content="A Nigerian Starstruck Engineer" />

    <meta property="og:title" content="Rho's Diary" />
    <meta property="og:description" content="A blog of a not so average teen" />

    <meta property="og:image" content="" />

    <link rel="icon" href="{% static 'img/favicon.png' %}" />


    <link rel="stylesheet" href="{% static 'css/split.css' %}" type="text/css" media="screen" />
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <style>
      .fs-split .split-image { background-image: url({{ writers.snap.url }}); background-position: center center; }   
    </style>
</head>

<body id="fullsingle" class="page-template-page-fullsingle-split">
  <div class="fs-split">
    <div class="split-image">
    </div>
    <div class="split-content" style="background-color: blueviolet;">
      <div class="split-content-vertically-center" style="background-color: blueviolet;" >
        <h1 style="text-align: center;">  <a href="/" style="color: ghostwhite;font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;"> RHO'S DIARY </a></h1><br>
        <div class="split-intro">
        <h1 style="color: ghostwhite;">{{ writers.first_name }} {{ writers.last_name }}</h1>
        <span class="tagline" style="color: cornsilk;">{{ writers.value_1 }}. {{ writers.value_2 }}. </span>
      </div>
  <div class="split-bio" >
  <p style="color: honeydew; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif">{{ writers.description }}</p>
</div>
  <div class="split-lists">
      <div class="split-list">
        <h3 style="color: honeydew;">Social</h3>
        <ul>
            <li ><a  style="color: lavender; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;" href="https://www.instagram.com/{{ writers.instagram}}/" target="_blank"> <i class="fab fa-instagram"></i>  @{{ writers.instagram }}</a></li>       
        </ul>
      </div>
      <div class="split-list">
        <h3  style="color: lavender;">Connect</h3>
        <ul>
            <li><a   style="color: lavender; font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;"href="mailto:{{ writers.email }}"> <i class="fas fa-envelope"></i> Email</a></li>
        </ul>
      </div>
    </div>
  </div>
  </div>

</div>
</body>
</html>

templates/author/connect.html
{% extends 'base.html' %}
{% block title %} 
    Rho'D Connect
{% endblock %}
{% load static %}
{% block content %}
	 <div class="parallax-container">
        <div class="parallax"><img src="{% static 'img/about.jpg' %}" class="responsive-img" style="filter:blur(3px);" ></div>
        <div  class="center-align">
            <h5>✍🏽💅🏽🙏🏽👩🏽‍🎓🩱💄💋💔💕</h5>
            <br>
            <br>
            <br>
            <h2 style="color: #c51162 ;">Who I   Am</h2>
            <h4 style="color: #651fff; font-family: cursive;"><p id="typo">...</p></h4>
        </div> 
    </div>

    <div class="container">
      <h2 class="left-align" style="color: rebeccapurple;">Rho's Diary</h2>
      <h6><blockquote>We are just a group of undergrads sharing our lives and how we survive it🤷🏽‍♀️🤷🏽‍♀️</blockquote></h6>

      <h4 class="left-align">Our Authors</h4>
      <div class="row">
        {% for writer in writers %}
        <div class="col s12 m6">
          <div class="card"> <a href="{{ writer.slug }}">
            <div class="card-image">
              <img src="{{ writer.snap.url }}" class="responsive-img">
              
              <a class="btn-floating halfway-fab waves-effect waves-purple purple darken-3" href="{{ writer.slug }}"> <i>@</i></a>
            </div>
            <div class="card-content">
              <span class="card-title" style="color: black;">{{ writer.first_name }} {{ writer.last_name }}</span>
              <p>I am {{ writer.first_name }},and this is my story.</p>
            </div>
          </div> </a>
        </div>
        {% endfor %}
      </div>  
    </div>
    <div class="parallax-container valign-wrapper" style=" height: 300px;">
      <div class="section no-pad-bot">
        <div class="container">
          <div class="row center">
            <h5 class="header col s12 light " style="color: cornsilk;">Thanks!!!! <p> Love from <a href="{{ writer.slug }}" style="color:thistle;"> Oghenerhona</a> and <a href="{{ writer.slug }}" style="color: rosybrown;"> Anirejuoriste</a></p></h5>
          </div>
        </div>
      </div>
      <div class="parallax"><img src="{% static 'img/overhead.jpg' %}" class="responsive-img"></div>
    </div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">  
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <script src="{% static 'js/all.js' %}"></script>  
    <script data-ad-client="ca-pub-3257133577264306" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
	<!--Navbar-->
    {% include 'partials/_navbar.html' %}
    {% block content %}

    {% endblock %}

	<!--Footer-->
	{% include 'partials/_footer.html' %}

    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/materialize.js' %}"></script>
    <script src="{% static 'js/typer.js' %}"></script>
    <script src="{% static 'js/app.js' %}"></script>
</body>
</html>

templates/blog/post.html
{% extends 'base.html' %}
{% block title %} 
    Rho's D | {{blog.blog_title}}
{% endblock %}
{% load static %}
{% load humanize %}
{% block content %}
	<div class="parallax-container valign-wrapper" style=" height: 300px;"style="filter:blur(2px);">
            <div class="section no-pad-bot">
              <div class="container">
                <div class="row center">
                  <h3 class="center-align" style="color: cornsilk;font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;">{{ blog.blog_title }}  -  Dear Diary {{ blog.id|apnumber }}</h3>
                </div>
              </div>
            </div>
            <div class="parallax"><img 
              {% if blog.blog_photo %} 
                srcset="{{ blog.blog_photo.url }}" class="responsive-img"
              {% else %}
                srcset="{% static 'img/overhead.jpg' %}" class="responsive-img"
              {% endif %}
              
              ></div>
              }
          </div>
          <div class="container">
            <blockquote>
              <h6>Jotted By <a href="/connect/{{ blog.blog_author.slug }}" style="font-family: Verdana, Geneva, Tahoma, sans-serif;color:darkmagenta;" target="_blank">{{ blog.blog_author }} </a></h6>
              <p>{{ blog.blog_time }}</p>
            </blockquote>
            <div class="tag">
              <div class="chip">
                <img src="{{ blog.blog_author.snap.url }}" alt="Author">
                 {{ blog.blog_author }}
              </div>
            </div>
            <br>
             <br>
            
            <div class="main">
              <p style="color:black">
                  {{ blog.blog_content |safe}}{{ form.media }}
                </p>
            </div>
            <br>
            <br>
            <br>
          </div>
{% endblock %}

templates/blog/posts.html
{% extends 'base.html' %}
{% block title %} 
    Rho's Secrets
{% endblock %}
{% load static %}
{% block content %}
	<div class="parallax-container">
        <div class="parallax"><img src="{% static 'img/blog.jpg' %}" class="responsive-img" style="filter: blur(2px); "></div>
        <div  class="center-align">
            <h5>✍🏽💅🏽🙏🏽👩🏽‍🎓🩱💄💋💔💕</h5>
            <br>
            <br>
            <br>
            <h2 style="color: #1a237e;">Diary Archives</h2>
            <h4 style="color: #1a237e;"><p>articles that touch</p></h4>
        </div> 
    </div>
    
    <div class="container">
        <div class="row">
          {% if article_content %}
              {% for article in article_content %}
              <div class="col s12 m6">   
                <div class="card">
                    <div class="card-image waves-effect waves-block waves-light">
                      <img class="activator"
                      {% if article.blog_photo %} 
                       srcset="{{ article.blog_photo.url }}" class="responsive-img"
                      {% else %}
                        srcset="{% static 'img/overhead.jpg' %}" class="responsive-img"
                      {% endif %}
                       >
                      
                    </div>
                    <div class="card-content">
                      <span class="card-title activator grey-text text-darken-4">{{ article.blog_title }}<div class="right">
                        <i class="fas fa-expand"></i></div></span>
                      <p><a href="{{ article.blog_url }}">Read more...</a></p>
                    </div>
                    <div class="card-reveal">
                      <span class="card-title grey-text text-darken-4">{{ article.blog_title }}<div class="right"><i class="fas fa-expand"></i></div></span>
                      <span class="card-title"><a href="/connect/{{ article.blog_author.slug }}" target="_blank" style="color: #303f9f;">
                      {{ article.blog_author }}</a></span>
                      <p>{{ article.short_description }}</p>
                    </div>
                  </div>
              </div>
           {% endfor %}
              {% else %}
                <h2>No Posts Available</h2>
            {% endif %}
          </div>
        {% if article_content.has_other_pages %}
          <ul class="pagination">
            {% if article_content.has_previous %}
              <li class="waves-effect waves-purple" ><a href="?page={{article_content.previous_page_number}}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><a>&laquo;</a></li>
            {%  endif %}
            {% for i in article_content.paginator.page_range %}
              {% if article_content.number == i %}
                <li class="active" style="background-color:#1a237e;"><a>{{ i }}</a></li>
              {% else %}
                <li class="waves-effect waves-purple" ><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if article_content.has_next %}
              <li class="waves-effect waves-purple" ><a href="?page={{article_content.next_page_number}}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><a>&raquo;</a></li>
            {%  endif %}
           <!-- 
            <li class="active" style="background-color:#1a237e;"><a href="#!">1</a></li>
            <li class="waves-effect waves-purple" ><a href="#!">2</a></li>
            <li class="waves-effect waves-purple"><a href="#!">&raquo;</a></li>
          </ul>-->
        {% endif %}
        </div>
    </div>
{% endblock %}

templates/main/home.html
{% extends 'base.html' %}
{% block title %} 
    Rho's Diary
{% endblock %}
{% load static %}

{% block content %}
<div class="parallax-container">
        <div class="parallax"><img src="{% static 'img/home.jpg' %}" class="responsive-img" style="filter: blur(1px); "></div>
        <div  class="center-align">
            <h5>✍🏽💅🏽🙏🏽👩🏽‍🎓🩱💄💋💔💕</h5>
        </div>
        <div class="flow-text"><h2 class="center-align" style="color: #1a237e">Dear Diary...</h2></div>
            <p class="flow-text"><b><h4 class="center-align" id="typer" style="color:  #5c6bc0; font-family: cursive;">...</h4></b></p>
    </div>

  
    <div class="container">
      <div class="row">
        {% if article_content %}
            {% for article in article_content %}
                <div class="col s12 m4">
                    <div class="card large hoverable">
                        <div class="card-image">
                            <img {% if article.blog_photo %} 
                               srcset="{{ article.blog_photo.url }}" class="responsive-img"
                              {% else %}
                                srcset ="{% static 'img/overhead.jpg' %}" class="responsive-img"
                              {% endif %}
                              
                             >
                            <span class="card-title">{{ article.blog_title }}</span>
                            
                        </div>
                        <div class="card-content">
                            <span class="card-title"><a href="connect/{{ article.blog_author.slug }}" target="_blank" style="color: #303f9f;">
                            {{ article.blog_author }}</a></span>
                            <p>{{ article.short_description }}</p>
                        </div>
                        <div class="card-action">
                            <a href="blog/{{ article.blog_url }}">Read more</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <h2>No Post Available</h2>
        {% endif %}
      </div>
      <a href="{% url 'blog:posts' %}" class="btn waves-effect waves-purple" style="background-color : #303f9f ">Read more..</a>
     
          
    </div>
 <br>
    <div class="parallax-container valign-wrapper" style=" height: 300px;">
        <div class="section no-pad-bot">
          <div class="container">
            <div class="row center">
              <h5 class="header col s12 light " style="color: cornsilk;">The average life of a Nigerian College student</h5>
            </div>
          </div>
        </div>
        <div class="parallax"><img src="{% static 'img/hike.jpg' %}" class="responsive-img"></div>
      </div>
{% endblock %}

templates/partials/_footer.html
    <footer class="page-footer indigo accent-3">
        <div class="footer-copyright" >
	            <div class="container" ><div class="center-align">
	            © <span id="date"></span> <a href="/connect/oghenerhona-ideh" style="color: white;">Oghenerhona</a> & <a href="/connect/the-geekish-nerd" style="color: white;">Anirejuoriste</a> Co.
	            </div>
        </div>
          </div>
    </footer>

templates/partials/_navbar.html
    <nav class="indigo lighten-1" role="navigation">
        <div class="nav-wrapper container"><a id="logo-container" href="{% url 'main:home' %}" class="brand-logo">Rho's Diary</a>
          <ul class="right hide-on-med-and-down">
            <li
            {% if '/' == request.path %}
              class="active"
            {% else %}
              class ="non-active"
            {% endif %}  
              ><a href="{% url 'main:home' %}">Home</a></li>
            <li 
            {% if 'blog' in request.path %}
              class="active"
            {% else %}
              class ="non-active"
            {% endif %}  
            ><a href="{% url 'blog:posts' %}">Blog</a></li>
            <li
              {% if 'connect' in request.path %}
              class="active"
            {% else %}
              class ="non-active"
            {% endif %} 
            ><a href="{% url 'author:connect' %}">Connect</a></li>
          </ul>
      
          <ul id="nav-mobile" class="sidenav" style=" background-color : #303f9f ">
            <li 
            {% if '/' == request.path %}
              class="active"
            {% else %}
              class ="non-active"
            {% endif %}  ><a href="{% url 'main:home' %}" style="color: azure;">Home</a></li>
            <li
            {% if 'blog' in request.path %}
              class="active"
            {% else %}
              class ="non-active"
            {% endif %} 
            ><a href="{% url 'blog:posts' %}" style="color: azure;">Blog</a></li>
            <li
            {% if 'connect' in request.path %}
              class="active"
            {% else %}
              class ="non-active"
            {% endif %} 
            ><a href="{% url 'author:connect' %}" style="color: azure;">Connect</a></li>
            <div class="divider" style="color: azure;"></div>
            {% for writer in writers %}
              <li><a
                   {% if 'connect' in request.path %}
              href="{{ writer.slug }}"
            {% else %}
              href="connect/{{ writer.slug }}"
            {% endif %} 
               style="color: azure;">{{ writer.first_name }}</a></li>
            {% endfor %}
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <div class="divider"></div>
            <li><a href="#" style="color: azure;">Dev by Eyimofe Ayo Pinnick</a></li>
          </ul>
          <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="fas fa-list"></i></a>
        </div>
      </nav>